# Generated by Django 5.2.7 on 2025-10-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriersite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
